namespace tinyUrl.Domain.DTOs
{
    public class UserModel
    {
        int userId { get; set; }
        string firstName { get; set; }
        string lastName { get; set; }

        //username is autonomously generated by the system
        string userName { get; set; }
        string email { get; set; }
        string password { get; set; }
        string confirmPassword { get; set; }

        //decided by admin , can be used for role-based access control (RBAC)
        string role { get; set; }
        string city { get; set; }
        string state { get; set; }
        string country { get; set; }
        long pincode { get; set; }
        long mobileNumber { get; set; }

    }
}
