namespace tinyUrl.Application.DTOs
{
    public class UserModel
    {
        public int userId { get; set; }
        public required string firstName { get; set; }
        public required string lastName { get; set; }

        //username is autonomously generated by the system
        public string userName { get; set; }
        public required string email { get; set; }
        public required string password { get; set; }
        public required string confirmPassword { get; set; }

        //decided by admin , can be used for role-based access control (RBAC)
        public string role { get; set; }
        public required string city { get; set; }
        public required string state { get; set; }
        public required string country { get; set; }
        public required long pincode { get; set; }
        public required long mobileNumber { get; set; }

    }
}
